# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - run: sudo apt-get update
        shell: bash
      - run: sudo apt-get install -y binfmt-support fdisk file kpartx qemu qemu-user-static unzip p7zip-full wget xz-utils units
        shell: bash
      - run: git clone https://github.com/Nature40/pimod.git         
      - run: sudo pimod/pimod.sh examples/RPi-RaspberryPi-OAK.Pifile
